version: '3.8'

services:
  node1:
    build: ./app
    container_name: protocol_node1
    ports:
      - "8081:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      protocol_net:
        ipv4_address: 172.20.0.10

  node2:
    build: ./app
    container_name: protocol_node2
    ports:
      - "8082:8080"
      - "5002:5000"
      - "5003:5001"
    networks:
      protocol_net:
        ipv4_address: 172.20.0.11

  node3:
    build: ./app
    container_name: protocol_node3
    ports:
      - "8083:8080"
      - "5004:5000"
      - "5005:5001"
    networks:
      protocol_net:
        ipv4_address: 172.20.0.12

networks:
  protocol_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
